"use strict";
var React = require("react");
var SequenceAligner = require("../lib/sequence_aligner.jsx");

// play with some data
var exampleData = {
	sequences: [
		{
			name: "S288C",
			sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
		},
		{
			name: "CEN.PK",
			sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACTAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
		},
		{
			name: "FL100",
			sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
		},
		{
			name: "D273-10B",
			sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
		},
		{
			name: "JK9-3D",
			sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
		},
		{
			name: "RM11-1a",
			sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
		},
		{
			name: "SK1",
			sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
		},
		{
			name: "W303",
			sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
		},
		{
			name: "Y55",
			sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
		}
	],
	segments: [
		{
			domain: [0, 88],
			visible: false
		},
		{
			domain: [88, 89],
			visible: true
		},
		{
			domain: [90, 354],
			visble: false
		}
	]
};

React.render(<SequenceAligner segments={exampleData.segments} sequences={exampleData.sequences}/>, document.getElementById("target"));
